### ISSUE TITLE
PhoneGap Build failed with error on Android

### ISSUE THREAD

**Issue by bloodcarter** [DevDmitryHub/cordova-plugin-appsflyer#5]
Here is the log:
```
Build Date: 2017-04-03 09:17:27 +0000
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "cordova.plugins.diagnostic.api-22@2.3.10-api-22" via npm
Installing "cordova.plugins.diagnostic.api-22" at "2.3.10-api-22" for android
Fetching plugin "cordova-plugin-whitelist@1.2.2" via npm
Installing "cordova-plugin-whitelist" at "1.2.2" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
Fetching plugin "cordova-plugin-inappbrowser@1.4.0" via npm
Installing "cordova-plugin-inappbrowser" at "1.4.0" for android
Fetching plugin "cordova-plugin-geolocation@2.2.0" via npm
Installing "cordova-plugin-geolocation" at "2.2.0" for android
Fetching plugin "cordova-plugin-compat" via npm
Installing "cordova-plugin-compat" at "1.1.0" for android
Fetching plugin "cordova-plugin-network-information@1.2.1" via npm
Installing "cordova-plugin-network-information" at "1.2.1" for android
Fetching plugin "cordova-plugin-google-analytics@0.8.1" via npm
Installing "cordova-plugin-google-analytics" at "0.8.1" for android
Subproject Path: CordovaLib
Fetching plugin "cordova-plugin-calendar@4.5.0" via npm
Installing "cordova-plugin-calendar" at "4.5.0" for android
Dependent plugin "cordova-plugin-compat" already installed on android.
Fetching plugin "cordova-plugin-x-socialsharing@5.1.1" via npm
Installing "cordova-plugin-x-socialsharing" at "5.1.1" for android
Fetching plugin "de.appplant.cordova.plugin.local-notification@0.8.4" via npm
Installing "de.appplant.cordova.plugin.local-notification" at "0.8.4" for android
Fetching plugin "cordova-plugin-device" via npm
Installing "cordova-plugin-device" at "1.1.5" for android
Fetching plugin "cordova-plugin-app-event" via npm
Installing "cordova-plugin-app-event" at "1.2.0" for android
Subproject Path: CordovaLib

        Your support is needed. If you use the local-notification plugin please support us in order to ensure further development.
        https://github.com/katzer/cordova-plugin-local-notifications#supporting

        Thank you!
Fetching plugin "cordova-plugin-splashscreen@3.2.2" via npm
Installing "cordova-plugin-splashscreen" at "3.2.2" for android
Fetching plugin "cordova-plugin-uniquedeviceid@1.3.2" via npm
Installing "cordova-plugin-uniquedeviceid" at "1.3.2" for android
Fetching plugin "cordova-plugin-appsflyer@~4.2.2" via npm
Installing "cordova-plugin-appsflyer" at "4.2.10" for android
Subproject Path: CordovaLib
Fetching plugin "phonegap-plugin-push" via npm
Installing "phonegap-plugin-push" at "1.10.0" for android
Subproject Path: CordovaLib
Fetching plugin "ionic-plugin-keyboard" via npm
Installing "ionic-plugin-keyboard" at "2.2.1" for android
Fetching plugin "cordova-plugin-statusbar" via npm
Installing "cordova-plugin-statusbar" at "2.2.2" for android
Fetching plugin "cordova-plugin-file" via npm
Installing "cordova-plugin-file" at "4.3.2" for android
Dependent plugin "cordova-plugin-compat" already installed on android.

The Android Persistent storage location now defaults to "Internal". Please check this plugin's README to see if your application needs any changes in its config.xml.

If this is a new application no changes are required.

If this is an update to an existing application that did not specify an "AndroidPersistentFileLocation" you may need to add:

      "<preference name="AndroidPersistentFileLocation" value="Compatibility" />"

to config.xml in order for the application to find previously stored files.
Plugin "cordova-plugin-device" already installed on android. Making it top-level.
Fetching plugin "cordova-plugin-file-transfer" via npm
Installing "cordova-plugin-file-transfer" at "1.6.2" for android
Dependent plugin "cordova-plugin-file" already installed on android.
--------------------------------------------------------------------------------
COMPILE OUTPUT
--------------------------------------------------------------------------------
Subproject Path: CordovaLib
Configuration on demand is an incubating feature.
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:preReleaseBuild UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugShaders
:CordovaLib:compileDebugShaders
:CordovaLib:generateDebugAssets
:CordovaLib:mergeDebugAssets
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:generateDebugBuildConfig
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:incrementalDebugJavaCompilationSafeguard
:CordovaLib:compileDebugJavaWithJavac
:CordovaLib:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
:CordovaLib:bundleDebug
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseShaders
:CordovaLib:compileReleaseShaders
:CordovaLib:generateReleaseAssets
:CordovaLib:mergeReleaseAssets
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:incrementalReleaseJavaCompilationSafeguard
:CordovaLib:compileReleaseJavaWithJavac
:CordovaLib:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
:CordovaLib:mergeReleaseJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
:CordovaLib:bundleRelease
:prepareComAndroidSupportSupportCompat2520Library
:prepareComAndroidSupportSupportCoreUi2520Library
:prepareComAndroidSupportSupportCoreUtils2520Library
:prepareComAndroidSupportSupportFragment2520Library
:prepareComAndroidSupportSupportMediaCompat2520Library
:prepareComAndroidSupportSupportV132340Library
:prepareComAndroidSupportSupportV42520Library
:prepareComGoogleAndroidGmsPlayServicesAds1020Library
:prepareComGoogleAndroidGmsPlayServicesAdsLite1020Library
:prepareComGoogleAndroidGmsPlayServicesAnalytics1020Library
:prepareComGoogleAndroidGmsPlayServicesAnalyticsImpl1020Library
:prepareComGoogleAndroidGmsPlayServicesBase1020Library
:prepareComGoogleAndroidGmsPlayServicesBasement1020Library
:prepareComGoogleAndroidGmsPlayServicesClearcut1020Library
:prepareComGoogleAndroidGmsPlayServicesGass1020Library
:prepareComGoogleAndroidGmsPlayServicesGcm1020Library
:prepareComGoogleAndroidGmsPlayServicesIid1020Library
:prepareComGoogleAndroidGmsPlayServicesTagmanagerV4Impl1020Library
:prepareComGoogleAndroidGmsPlayServicesTasks1020Library
:prepareMeLeolinShortcutBadger1112Library
:prepareProjectCordovaLibUnspecifiedDebugLibrary
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
:processDebugManifest
:processDebugResourcesWarning: AndroidManifest.xml already defines debuggable (in http://schemas.android.com/apk/res/android); using existing value in manifest.


:generateDebugSources
:incrementalDebugJavaCompilationSafeguard
:compileDebugJavaWithJavac
:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/project/src/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java:16: error: cannot find symbol
import com.appsflyer.AppsFlyerConversionListener;
                    ^
  symbol:   class AppsFlyerConversionListener
  location: package com.appsflyer
/project/src/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java:17: error: cannot find symbol
import com.appsflyer.AppsFlyerLib;
                    ^
  symbol:   class AppsFlyerLib
  location: package com.appsflyer
/project/src/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java:136: error: cannot find symbol
	private void registerConversionListener(AppsFlyerLib instance){
	                                        ^
  symbol:   class AppsFlyerLib
  location: class AppsFlyerPlugin
/project/src/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java:41: error: cannot find symbol
		AppsFlyerLib.getInstance().sendDeepLinkData(cordova.getActivity());
		^
  symbol:   variable AppsFlyerLib
  location: class AppsFlyerPlugin
/project/src/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java:77: error: cannot find symbol
        AppsFlyerLib.getInstance().trackEvent(c, null, null);
        ^
  symbol:   variable AppsFlyerLib
  location: class AppsFlyerPlugin
/project/src/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java:92: error: cannot find symbol
		AppsFlyerLib instance = AppsFlyerLib.getInstance();
		^
  symbol:   class AppsFlyerLib
  location: class AppsFlyerPlugin
/project/src/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java:92: error: cannot find symbol
		AppsFlyerLib instance = AppsFlyerLib.getInstance();
		                        ^
  symbol:   variable AppsFlyerLib
  location: class AppsFlyerPlugin
/project/src/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java:137: error: cannot find symbol
		instance.registerConversionListener(cordova.getActivity().getApplicationContext(), new AppsFlyerConversionListener(){
		                                                                                       ^
  symbol:   class AppsFlyerConversionListener
  location: class AppsFlyerPlugin
/project/src/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java:227: error: cannot find symbol
		AppsFlyerLib.getInstance().trackEvent(c, eventName, eventValues);
		^
  symbol:   variable AppsFlyerLib
  location: class AppsFlyerPlugin
/project/src/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java:248: error: cannot find symbol
		AppsFlyerLib.getInstance().setCurrencyCode(currencyId);
		^
  symbol:   variable AppsFlyerLib
  location: class AppsFlyerPlugin
/project/src/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java:262: error: cannot find symbol
        	AppsFlyerLib.getInstance().setAppUserId(customeUserId);
        	^
  symbol:   variable AppsFlyerLib
  location: class AppsFlyerPlugin
/project/src/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java:278: error: cannot find symbol
    	String id = AppsFlyerLib.getInstance().getAppsFlyerUID(cordova.getActivity().getApplicationContext());
    	            ^
  symbol:   variable AppsFlyerLib
  location: class AppsFlyerPlugin
/project/src/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java:317: error: cannot find symbol
		AppsFlyerLib.getInstance().setGCMProjectNumber(c, gcmProjectId);
		^
  symbol:   variable AppsFlyerLib
  location: class AppsFlyerPlugin
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
13 errors
:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.189 secs
Error: /project/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Warning: AndroidManifest.xml already defines debuggable (in http://schemas.android.com/apk/res/android); using existing value in manifest.

/project/src/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java:16: error: cannot find symbol
import com.appsflyer.AppsFlyerConversionListener;
                    ^
  symbol:   class AppsFlyerConversionListener
  location: package com.appsflyer
/project/src/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java:17: error: cannot find symbol
import com.appsflyer.AppsFlyerLib;
                    ^
  symbol:   class AppsFlyerLib
  location: package com.appsflyer
/project/src/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java:136: error: cannot find symbol
	private void registerConversionListener(AppsFlyerLib instance){
	                                        ^
  symbol:   class AppsFlyerLib
  location: class AppsFlyerPlugin
/project/src/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java:41: error: cannot find symbol
		AppsFlyerLib.getInstance().sendDeepLinkData(cordova.getActivity());
		^
  symbol:   variable AppsFlyerLib
  location: class AppsFlyerPlugin
/project/src/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java:77: error: cannot find symbol
        AppsFlyerLib.getInstance().trackEvent(c, null, null);
        ^
  symbol:   variable AppsFlyerLib
  location: class AppsFlyerPlugin
/project/src/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java:92: error: cannot find symbol
		AppsFlyerLib instance = AppsFlyerLib.getInstance();
		^
  symbol:   class AppsFlyerLib
  location: class AppsFlyerPlugin
/project/src/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java:92: error: cannot find symbol
		AppsFlyerLib instance = AppsFlyerLib.getInstance();
		                        ^
  symbol:   variable AppsFlyerLib
  location: class AppsFlyerPlugin
/project/src/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java:137: error: cannot find symbol
		instance.registerConversionListener(cordova.getActivity().getApplicationContext(), new AppsFlyerConversionListener(){
		                                                                                       ^
  symbol:   class AppsFlyerConversionListener
  location: class AppsFlyerPlugin
/project/src/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java:227: error: cannot find symbol
		AppsFlyerLib.getInstance().trackEvent(c, eventName, eventValues);
		^
  symbol:   variable AppsFlyerLib
  location: class AppsFlyerPlugin
/project/src/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java:248: error: cannot find symbol
		AppsFlyerLib.getInstance().setCurrencyCode(currencyId);
		^
  symbol:   variable AppsFlyerLib
  location: class AppsFlyerPlugin
/project/src/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java:262: error: cannot find symbol
        	AppsFlyerLib.getInstance().setAppUserId(customeUserId);
        	^
  symbol:   variable AppsFlyerLib
  location: class AppsFlyerPlugin
/project/src/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java:278: error: cannot find symbol
    	String id = AppsFlyerLib.getInstance().getAppsFlyerUID(cordova.getActivity().getApplicationContext());
    	            ^
  symbol:   variable AppsFlyerLib
  location: class AppsFlyerPlugin
/project/src/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java:317: error: cannot find symbol
		AppsFlyerLib.getInstance().setGCMProjectNumber(c, gcmProjectId);
		^
  symbol:   variable AppsFlyerLib
  location: class AppsFlyerPlugin
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
13 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by DevDmitryHub** [comment]
Hi, try to use the latest version: `v.4.2.17` with fix - cfa67b9ff3876232f783ef7deaee5cda30709623
